### ISSUE TITLE
[FIX] Componente lista suspensa (app)

### ISSUE THREAD

**Issue by YuriTobias** [VRI-UFPR/CienciaNaEscola#222]
- Texto dos inputs não está aparecendo;

**Comment by m-piovesan** [comment]
![image](https://github.com/VRI-UFPR/CienciaNaEscola/assets/97471131/58140641-7c24-4c49-b632-4878b3462efb)
manos não sei se realmente tá quebrado ou eu que fiz algo meio doido?

**Comment by m-piovesan** [comment]
`case 2:
                            return (
                                <div key={input.id} className="row justify-content-center m-0 pt-3">
                                    {<SelectInput input={{question: 'Pergunta', options: [
                                      { value: 1, label: 'Teste' },
                                      { value: 2, label: 'Mais um Teste' },
                                      { value: 3, label: 'Another' },
                                    ] }} />}
                                </div>
                            );`

**Comment by m-piovesan** [comment]
![code](https://github.com/VRI-UFPR/CienciaNaEscola/assets/97471131/6e047718-03c6-44b2-9bce-300f98d3c585)
fiz assim para testar

**Comment by YuriTobias** [comment]
Piá, pior que agora nem eu entendi essa kkkk, mas de fato, tá funcionando mesmo!
