### ISSUE TITLE
[FIX] Revisão componente localização - App

### ISSUE THREAD

**Issue by IosBonaldi** [VRI-UFPR/CienciaNaEscola#65]
![image](https://user-images.githubusercontent.com/43620413/231313138-adf3cd47-3bb9-4d20-93de-060c68128036.png)

**Comment by YuriTobias** [comment]
> ![image](https://user-images.githubusercontent.com/43620413/231313138-adf3cd47-3bb9-4d20-93de-060c68128036.png)

- É importante/necessário revisar o design vide novas sugestões (presentes no backlog);
